name: Node.js CI

on: [push, pull_request]

jobs:
  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Build
        run: |
          npm run --if-present build
          node index.js
          npm pack
          npm exec npm-pkg-lint
      - run: npm test

  lerna:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lerna-version: [3.x, 4.x, 5.x, 6.x, 7.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v3
      - name: Build
        run: |
          npm ci
          npm run build --if-present
      - name: Install lerna v${{ matrix.lerna-version }}
        run: |
          npm install $(npx -y npm-min-peer lerna --major ${{ matrix.lerna-version }} --with-name)
          npm ls lerna
      - name: Integration test
        run: npm exec jest --no-coverage integration

  semantic-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sr-version: [20.x, 21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v3
      - name: Build
        run: |
          npm ci
          npm run build --if-present
      - name: Install semantic-release v${{ matrix.sr-version }}
        run: |
          npm install $(npx -y npm-min-peer semantic-release --major ${{ matrix.sr-version }} --with-name)
          npm ls semantic-release
      - name: Integration test
        run: npm exec jest --no-coverage integration
